<?php

namespace App;


use App\Notifications\Events\UserWasSubscribeToEvent;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

/**
 * App\EventSubscription
 *
 * @property-read \App\Event $event
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @property-read \App\User $user
 * @mixin \Eloquent
 */
class EventSubscription extends Model
{
    use Notifiable;

    static protected function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function($eventSubscription){
            // send notification to event creator
            $eventSubscription->event->user->notify(new UserWasSubscribeToEvent($eventSubscription));

            // send notification to user subscription
            $eventSubscription->user->notify(new UserWasSubscribeToEvent($eventSubscription));
        });

    }


    protected $guarded = [];

    // Subscribe user
    public function user() {
        return $this->belongsTo(User::class);
    }

    // Event
    public function event() {
        return $this->belongsTo(Event::class);
    }


}
