<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Notifications\Messenger\UserSendNewMessage;
use Illuminate\Notifications\Notifiable;

/**
 * App\Messenger
 *
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @property-read \App\User $owner
 * @property-read \App\User $user
 * @mixin \Eloquent
 */
class Messenger extends Model
{
    use Notifiable;

    protected $guarded = [];

    static protected function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function($message){
            $message->user->notify(new UserSendNewMessage($message));
        });

    }

    public function user()
    {
        return $this->belongsTo(User::class, 'requested_user');
    }

    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }


}
